#

source 'https://rubygems.org'

gem 'sinatra', '1.4.8'
gem 'sinatra-contrib'

gem 'activerecord', require: 'active_record'
gem 'connection_pool'
gem 'hiredis'
# gem 'mysql2'
# gem 'oj'
gem 'redis'
# gem 'dalli'
# gem 'memcached_store'
# gem 'lock_and_cache'
gem 'rest-client'
gem 'pg'
# gem 'puma'
# gem 'racksh'
# gem 'redis-activesupport'
gem 'thin'
