#

source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'activerecord', require: 'active_record'
gem 'connection_pool'
gem 'hiredis'
gem 'http'
# gem 'mysql2'
# gem 'oj'
gem 'redis'
# gem 'dalli'
# gem 'memcached_store'
# gem 'lock_and_cache'
gem 'pg'
# gem 'rhebok'
# gem 'racksh'
# gem 'redis-activesupport'
# gem 'thin'
# gem 'sleepy_penguin'
# gem 'sendfile'
# gem 'rainbows'

# gem 'puma'
gem 'agoo'
